name: "composite"
description: "composite"
inputs:
  maximize-space:
    description: "maximize-space"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - if: ${{ inputs.maximize-space == 'true' }}
      uses: AdityaGarg8/remove-unwanted-software@master
      with:
        remove-android: true
        remove-dotnet: true
        remove-haskell: true
        remove-docker-images: true
        remove-codeql: true
        remove-large-packages: true
        remove-cached-tools: true
        remove-swapfile: true
    - shell: bash
      run: |
        sudo fallocate -l 8G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo chmod 1777 /mnt
        sudo mkdir -p /mnt/tmp
        sudo chmod 1777 /mnt/tmp
        sudo mount --bind /mnt/tmp /tmp
        sudo mkdir -p /nix
        sudo mkdir -p /mnt/nix
        sudo mount --bind /mnt/nix /nix
        sudo mount -o remount,size=12G /dev/shm
        df -h
        free
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable-small
        extra_nix_config: |
          auto-optimise-store = true
          always-allow-substitutes = true
          builders-use-substitutes = true
          min-free = 10240
          download-buffer-size = 134217728
          build-dir = /tmp
          require-sigs = false
          sandbox = true
          show-trace = true
          warn-dirty = false
          use-registries = false
          use-cgroups = true
          experimental-features = nix-command flakes cgroups git-hashing dynamic-derivations ca-derivations
          extra-substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.garnix.io https://cache.ngi0.nixos.org https://nanari.cachix.org
          extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.ngi0.nixos.org-1:KqH5CBLNSyX184S9BKZJo1LxrxJ9ltnY2uAs5c/f1MA= nanari.cachix.org-1:g2X+SmJHsI0siZez0IUUgVyOuvPG5CWhrhoE11MqALA=
    - uses: DeterminateSystems/magic-nix-cache-action@v8
      with:
        diagnostic-endpoint: ""
        use-flakehub: false
    - uses: extractions/setup-just@v2
    - shell: bash
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
