name: build

on:
  workflow_dispatch:
    inputs:
      sshx:
        description: "sshx"
        required: false
        default: false
        type: boolean

env:
  TMPDIR: "/tmp"
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/composite
      - uses: cachix/cachix-action@v15
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - if: ${{ inputs.sshx }}
        run: curl -sSf https://sshx.io/get | sh -s run
      - if: ${{ !inputs.sshx }}
        run: |
          nix-env -i nixos-rebuild-ng -f '<nixpkgs>'
          just build-os
        # nix build "github:NixOS/nixpkgs/nixos-unstable#lix" --impure --show-trace -L -v
        # nix-shell maintainers/scripts/update.nix --argstr package mihomo-party --argstr commit true
