name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          diagnostic-endpoint: ""
          use-flakehub: false

      - uses: AdityaGarg8/remove-unwanted-software@master
        with:
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-docker-images: true
          remove-codeql: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true

      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - run: just build-os
