name: build

on:
  workflow_dispatch:
    inputs:
      sshx:
        description: "sshx"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            extra-substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.garnix.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          diagnostic-endpoint: ""
          use-flakehub: false

      - uses: AdityaGarg8/remove-unwanted-software@master
        with:
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-docker-images: true
          remove-codeql: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true

      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - if: ${{ inputs.sshx }}
        run: curl -sSf https://sshx.io/get | sh -s run
      # ulimit -v 6291456
      # NIX_BUILD_CORES=3 nix build "github:NixOS/nixpkgs/nixos-unstable#nix" --impure --show-trace -L -v --option extra-substituters "https://mirrors.ustc.edu.cn/nix-channels/store https://cache.nixos.org https://nix-community.cachix.org https://cache.garnix.io" --option trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g="

      - if: ${{ !inputs.sshx }}
        run: just build-os
