name: check

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TMPDIR: "/tmp"
  NIXPKGS_ALLOW_UNFREE: 1
  NIXPKGS_ACCEPT_ANDROID_SDK_LICENSE: 1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/composite
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          task fmt
          task check
