name: format

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
            extra-substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.garnix.io

      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          diagnostic-endpoint: ""
          use-flakehub: false

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: nix fmt --no-write-lock-file --show-trace -L -v

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: fmt
          branch: fmt
          delete-branch: true
          title: "fmt"
          body: fmt
          labels: |
            fmt
            automated pr
