name: pkg

on:
  workflow_dispatch:
    inputs:
      package:
        description: "package name"
        required: true
        default: ""
        type: string

env:
  TMPDIR: "/tmp"
  NIXPKGS_ALLOW_UNFREE: 1

jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/composite
      - uses: cachix/cachix-action@v15
        with:
          name: ${{ secrets.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: just build $PACKAGE
        env:
          PACKAGE: ${{ inputs.package }}
